package com.swp391.onlinetutorapplication.onlinetutorapplication.security.forumService.forumServiceImplement;

import com.swp391.onlinetutorapplication.onlinetutorapplication.security.forumService.forumServiceInterface.QuestionServiceInterface;

public class QuestionServiceImplement implements QuestionServiceInterface {
}
